# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainsettingdialog_ui.ui',
# licensing of 'mainsettingdialog_ui.ui' applies.
#
# Created: Sun Jun  2 18:59:43 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainsettingDialog(object):
    def setupUi(self, mainsettingDialog):
        mainsettingDialog.setObjectName("mainsettingDialog")
        mainsettingDialog.resize(860, 570)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainsettingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_Options = QtWidgets.QListWidget(mainsettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Options.sizePolicy().hasHeightForWidth())
        self.listWidget_Options.setSizePolicy(sizePolicy)
        self.listWidget_Options.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidget_Options.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget_Options.setObjectName("listWidget_Options")
        QtWidgets.QListWidgetItem(self.listWidget_Options)
        QtWidgets.QListWidgetItem(self.listWidget_Options)
        QtWidgets.QListWidgetItem(self.listWidget_Options)
        QtWidgets.QListWidgetItem(self.listWidget_Options)
        self.horizontalLayout_2.addWidget(self.listWidget_Options)
        self.stackedWidget_Options = QtWidgets.QStackedWidget(mainsettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_Options.sizePolicy().hasHeightForWidth())
        self.stackedWidget_Options.setSizePolicy(sizePolicy)
        self.stackedWidget_Options.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget_Options.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget_Options.setLineWidth(5)
        self.stackedWidget_Options.setObjectName("stackedWidget_Options")
        self.defaults_Columns = QtWidgets.QWidget()
        self.defaults_Columns.setObjectName("defaults_Columns")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.defaults_Columns)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_restore_columns = QtWidgets.QPushButton(self.defaults_Columns)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_restore_columns.setFont(font)
        self.pushButton_restore_columns.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_restore_columns.setObjectName("pushButton_restore_columns")
        self.horizontalLayout_9.addWidget(self.pushButton_restore_columns)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.listWidget_mod = QtWidgets.QListWidget(self.defaults_Columns)
        self.listWidget_mod.setObjectName("listWidget_mod")
        self.gridLayout_10.addWidget(self.listWidget_mod, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_up = QtWidgets.QPushButton(self.defaults_Columns)
        self.pushButton_up.setAutoDefault(False)
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout_3.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.defaults_Columns)
        self.pushButton_down.setAutoDefault(False)
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout_3.addWidget(self.pushButton_down)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.label_Selected = QtWidgets.QLabel(self.defaults_Columns)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Selected.setFont(font)
        self.label_Selected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Selected.setObjectName("label_Selected")
        self.gridLayout_10.addWidget(self.label_Selected, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_remove = QtWidgets.QPushButton(self.defaults_Columns)
        self.pushButton_remove.setAutoDefault(False)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout_2.addWidget(self.pushButton_remove)
        self.pushButton_add = QtWidgets.QPushButton(self.defaults_Columns)
        self.pushButton_add.setAutoDefault(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.listWidget_org = QtWidgets.QListWidget(self.defaults_Columns)
        self.listWidget_org.setObjectName("listWidget_org")
        self.gridLayout_10.addWidget(self.listWidget_org, 1, 3, 1, 1)
        self.label_Nonselective = QtWidgets.QLabel(self.defaults_Columns)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Nonselective.setFont(font)
        self.label_Nonselective.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Nonselective.setObjectName("label_Nonselective")
        self.gridLayout_10.addWidget(self.label_Nonselective, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.defaults_Columns)
        self.frame_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 2, 0, 1, 1)
        self.label_DD = QtWidgets.QLabel(self.defaults_Columns)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DD.setFont(font)
        self.label_DD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DD.setObjectName("label_DD")
        self.gridLayout_2.addWidget(self.label_DD, 0, 0, 1, 1)
        self.stackedWidget_Options.addWidget(self.defaults_Columns)
        self.defaults_Thumbnail = QtWidgets.QWidget()
        self.defaults_Thumbnail.setObjectName("defaults_Thumbnail")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.defaults_Thumbnail)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_restore_thumb = QtWidgets.QPushButton(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_restore_thumb.sizePolicy().hasHeightForWidth())
        self.pushButton_restore_thumb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_restore_thumb.setFont(font)
        self.pushButton_restore_thumb.setObjectName("pushButton_restore_thumb")
        self.gridLayout_3.addWidget(self.pushButton_restore_thumb, 7, 1, 1, 1)
        self.groupBox_Thumbnailsize = QtWidgets.QGroupBox(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Thumbnailsize.sizePolicy().hasHeightForWidth())
        self.groupBox_Thumbnailsize.setSizePolicy(sizePolicy)
        self.groupBox_Thumbnailsize.setObjectName("groupBox_Thumbnailsize")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Thumbnailsize)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_y = QtWidgets.QLineEdit(self.groupBox_Thumbnailsize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_y.sizePolicy().hasHeightForWidth())
        self.lineEdit_y.setSizePolicy(sizePolicy)
        self.lineEdit_y.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.gridLayout.addWidget(self.lineEdit_y, 2, 1, 1, 1)
        self.lineEdit_x = QtWidgets.QLineEdit(self.groupBox_Thumbnailsize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_x.sizePolicy().hasHeightForWidth())
        self.lineEdit_x.setSizePolicy(sizePolicy)
        self.lineEdit_x.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_x.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.gridLayout.addWidget(self.lineEdit_x, 1, 1, 1, 1)
        self.label_y = QtWidgets.QLabel(self.groupBox_Thumbnailsize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_y.sizePolicy().hasHeightForWidth())
        self.label_y.setSizePolicy(sizePolicy)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 2, 0, 1, 1)
        self.label_x = QtWidgets.QLabel(self.groupBox_Thumbnailsize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_x.sizePolicy().hasHeightForWidth())
        self.label_x.setSizePolicy(sizePolicy)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_Thumbnailsize, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_stafps = QtWidgets.QLabel(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stafps.sizePolicy().hasHeightForWidth())
        self.label_stafps.setSizePolicy(sizePolicy)
        self.label_stafps.setObjectName("label_stafps")
        self.horizontalLayout_3.addWidget(self.label_stafps)
        self.lineEdit_stafps = QtWidgets.QLineEdit(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_stafps.sizePolicy().hasHeightForWidth())
        self.lineEdit_stafps.setSizePolicy(sizePolicy)
        self.lineEdit_stafps.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_stafps.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_stafps.setMaxLength(6)
        self.lineEdit_stafps.setFrame(True)
        self.lineEdit_stafps.setObjectName("lineEdit_stafps")
        self.horizontalLayout_3.addWidget(self.lineEdit_stafps)
        self.label_stafps2 = QtWidgets.QLabel(self.defaults_Thumbnail)
        self.label_stafps2.setObjectName("label_stafps2")
        self.horizontalLayout_3.addWidget(self.label_stafps2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 5, 1, 1, 2)
        self.groupBox_ThumbnailParam = QtWidgets.QGroupBox(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ThumbnailParam.sizePolicy().hasHeightForWidth())
        self.groupBox_ThumbnailParam.setSizePolicy(sizePolicy)
        self.groupBox_ThumbnailParam.setObjectName("groupBox_ThumbnailParam")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_ThumbnailParam)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_Bright = QtWidgets.QLabel(self.groupBox_ThumbnailParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Bright.sizePolicy().hasHeightForWidth())
        self.label_Bright.setSizePolicy(sizePolicy)
        self.label_Bright.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_Bright.setObjectName("label_Bright")
        self.gridLayout_6.addWidget(self.label_Bright, 0, 0, 1, 1)
        self.lineEdit_Bright = QtWidgets.QLineEdit(self.groupBox_ThumbnailParam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Bright.sizePolicy().hasHeightForWidth())
        self.lineEdit_Bright.setSizePolicy(sizePolicy)
        self.lineEdit_Bright.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_Bright.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Bright.setObjectName("lineEdit_Bright")
        self.gridLayout_6.addWidget(self.lineEdit_Bright, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ThumbnailParam, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.defaults_Thumbnail)
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3.addWidget(self.frame_3, 6, 1, 1, 2)
        self.groupBox_ThumbnailOffset = QtWidgets.QGroupBox(self.defaults_Thumbnail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ThumbnailOffset.sizePolicy().hasHeightForWidth())
        self.groupBox_ThumbnailOffset.setSizePolicy(sizePolicy)
        self.groupBox_ThumbnailOffset.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_ThumbnailOffset.setObjectName("groupBox_ThumbnailOffset")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_ThumbnailOffset)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_End = QtWidgets.QLineEdit(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_End.sizePolicy().hasHeightForWidth())
        self.lineEdit_End.setSizePolicy(sizePolicy)
        self.lineEdit_End.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_End.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_End.setObjectName("lineEdit_End")
        self.gridLayout_4.addWidget(self.lineEdit_End, 2, 1, 1, 1)
        self.lineEdit_Center = QtWidgets.QLineEdit(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Center.sizePolicy().hasHeightForWidth())
        self.lineEdit_Center.setSizePolicy(sizePolicy)
        self.lineEdit_Center.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Center.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Center.setObjectName("lineEdit_Center")
        self.gridLayout_4.addWidget(self.lineEdit_Center, 1, 1, 1, 1)
        self.lineEdit_Start = QtWidgets.QLineEdit(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Start.sizePolicy().hasHeightForWidth())
        self.lineEdit_Start.setSizePolicy(sizePolicy)
        self.lineEdit_Start.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Start.setObjectName("lineEdit_Start")
        self.gridLayout_4.addWidget(self.lineEdit_Start, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_ThumbnailOffset)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.label_Soffset = QtWidgets.QLabel(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Soffset.sizePolicy().hasHeightForWidth())
        self.label_Soffset.setSizePolicy(sizePolicy)
        self.label_Soffset.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Soffset.setObjectName("label_Soffset")
        self.gridLayout_4.addWidget(self.label_Soffset, 0, 0, 1, 1)
        self.label_Eoffset = QtWidgets.QLabel(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Eoffset.sizePolicy().hasHeightForWidth())
        self.label_Eoffset.setSizePolicy(sizePolicy)
        self.label_Eoffset.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Eoffset.setObjectName("label_Eoffset")
        self.gridLayout_4.addWidget(self.label_Eoffset, 2, 0, 1, 1)
        self.label_Coffset = QtWidgets.QLabel(self.groupBox_ThumbnailOffset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Coffset.sizePolicy().hasHeightForWidth())
        self.label_Coffset.setSizePolicy(sizePolicy)
        self.label_Coffset.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Coffset.setObjectName("label_Coffset")
        self.gridLayout_4.addWidget(self.label_Coffset, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ThumbnailOffset, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        self.stackedWidget_Options.addWidget(self.defaults_Thumbnail)
        self.defaults_xlsx = QtWidgets.QWidget()
        self.defaults_xlsx.setObjectName("defaults_xlsx")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.defaults_xlsx)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.defaults_xlsx)
        self.frame_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(3)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8.addWidget(self.frame_4, 1, 0, 1, 1)
        self.groupBox_xlsxout = QtWidgets.QGroupBox(self.defaults_xlsx)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_xlsxout.setFont(font)
        self.groupBox_xlsxout.setObjectName("groupBox_xlsxout")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_xlsxout)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_Note2 = QtWidgets.QLabel(self.groupBox_xlsxout)
        self.label_Note2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Note2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Note2.setWordWrap(True)
        self.label_Note2.setObjectName("label_Note2")
        self.gridLayout_9.addWidget(self.label_Note2, 6, 0, 1, 1)
        self.label_Note = QtWidgets.QLabel(self.groupBox_xlsxout)
        self.label_Note.setObjectName("label_Note")
        self.gridLayout_9.addWidget(self.label_Note, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_book = QtWidgets.QRadioButton(self.groupBox_xlsxout)
        self.radioButton_book.setAutoExclusive(True)
        self.radioButton_book.setObjectName("radioButton_book")
        self.verticalLayout_4.addWidget(self.radioButton_book)
        self.radioButton_sheet = QtWidgets.QRadioButton(self.groupBox_xlsxout)
        self.radioButton_sheet.setAutoExclusive(True)
        self.radioButton_sheet.setObjectName("radioButton_sheet")
        self.verticalLayout_4.addWidget(self.radioButton_sheet)
        self.radioButton_all = QtWidgets.QRadioButton(self.groupBox_xlsxout)
        self.radioButton_all.setAutoExclusive(True)
        self.radioButton_all.setObjectName("radioButton_all")
        self.verticalLayout_4.addWidget(self.radioButton_all)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Maxrow = QtWidgets.QLabel(self.groupBox_xlsxout)
        self.label_Maxrow.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_Maxrow.setObjectName("label_Maxrow")
        self.horizontalLayout_4.addWidget(self.label_Maxrow)
        self.spinBox_maxrows = QtWidgets.QSpinBox(self.groupBox_xlsxout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_maxrows.sizePolicy().hasHeightForWidth())
        self.spinBox_maxrows.setSizePolicy(sizePolicy)
        self.spinBox_maxrows.setObjectName("spinBox_maxrows")
        self.horizontalLayout_4.addWidget(self.spinBox_maxrows)
        spacerItem4 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 7, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_xlsxout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_restore_xlsx = QtWidgets.QPushButton(self.defaults_xlsx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_restore_xlsx.sizePolicy().hasHeightForWidth())
        self.pushButton_restore_xlsx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_restore_xlsx.setFont(font)
        self.pushButton_restore_xlsx.setObjectName("pushButton_restore_xlsx")
        self.horizontalLayout_5.addWidget(self.pushButton_restore_xlsx)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.stackedWidget_Options.addWidget(self.defaults_xlsx)
        self.defaults_Misc = QtWidgets.QWidget()
        self.defaults_Misc.setObjectName("defaults_Misc")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.defaults_Misc)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_all_restore = QtWidgets.QPushButton(self.defaults_Misc)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_all_restore.setFont(font)
        self.pushButton_all_restore.setObjectName("pushButton_all_restore")
        self.horizontalLayout_7.addWidget(self.pushButton_all_restore)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 7, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.defaults_Misc)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.gridLayout_5.addWidget(self.frame, 5, 0, 1, 1)
        self.groupBox_misc = QtWidgets.QGroupBox(self.defaults_Misc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_misc.sizePolicy().hasHeightForWidth())
        self.groupBox_misc.setSizePolicy(sizePolicy)
        self.groupBox_misc.setMaximumSize(QtCore.QSize(16777215, 270))
        self.groupBox_misc.setAutoFillBackground(False)
        self.groupBox_misc.setTitle("")
        self.groupBox_misc.setFlat(False)
        self.groupBox_misc.setObjectName("groupBox_misc")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_misc)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.checkBox_Disableseq = QtWidgets.QCheckBox(self.groupBox_misc)
        self.checkBox_Disableseq.setObjectName("checkBox_Disableseq")
        self.gridLayout_11.addWidget(self.checkBox_Disableseq, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_checksum = QtWidgets.QComboBox(self.groupBox_misc)
        self.comboBox_checksum.setObjectName("comboBox_checksum")
        self.comboBox_checksum.addItem("")
        self.comboBox_checksum.addItem("")
        self.comboBox_checksum.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_checksum, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 0, 2, 1, 1)
        self.label_checksum = QtWidgets.QLabel(self.groupBox_misc)
        self.label_checksum.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_checksum.setObjectName("label_checksum")
        self.gridLayout_7.addWidget(self.label_checksum, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_eyecatch = QtWidgets.QHBoxLayout()
        self.horizontalLayout_eyecatch.setContentsMargins(0, -1, 5, -1)
        self.horizontalLayout_eyecatch.setObjectName("horizontalLayout_eyecatch")
        self.label_eyecatch = QtWidgets.QLabel(self.groupBox_misc)
        self.label_eyecatch.setObjectName("label_eyecatch")
        self.horizontalLayout_eyecatch.addWidget(self.label_eyecatch)
        self.pushButton_eyecatch = QtWidgets.QPushButton(self.groupBox_misc)
        self.pushButton_eyecatch.setObjectName("pushButton_eyecatch")
        self.horizontalLayout_eyecatch.addWidget(self.pushButton_eyecatch)
        self.lineEdit_eyecatch = QtWidgets.QLineEdit(self.groupBox_misc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_eyecatch.sizePolicy().hasHeightForWidth())
        self.lineEdit_eyecatch.setSizePolicy(sizePolicy)
        self.lineEdit_eyecatch.setObjectName("lineEdit_eyecatch")
        self.horizontalLayout_eyecatch.addWidget(self.lineEdit_eyecatch)
        self.gridLayout_11.addLayout(self.horizontalLayout_eyecatch, 2, 0, 1, 1)
        self.checkBox_lang = QtWidgets.QCheckBox(self.groupBox_misc)
        self.checkBox_lang.setObjectName("checkBox_lang")
        self.gridLayout_11.addWidget(self.checkBox_lang, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_restore_misc = QtWidgets.QPushButton(self.groupBox_misc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_restore_misc.sizePolicy().hasHeightForWidth())
        self.pushButton_restore_misc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_restore_misc.setFont(font)
        self.pushButton_restore_misc.setAutoDefault(False)
        self.pushButton_restore_misc.setObjectName("pushButton_restore_misc")
        self.horizontalLayout_6.addWidget(self.pushButton_restore_misc)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_misc, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem11, 1, 0, 1, 1)
        self.stackedWidget_Options.addWidget(self.defaults_Misc)
        self.horizontalLayout_2.addWidget(self.stackedWidget_Options)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_save = QtWidgets.QPushButton(mainsettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(mainsettingDialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem12 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(mainsettingDialog)
        self.stackedWidget_Options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainsettingDialog)
        mainsettingDialog.setTabOrder(self.listWidget_Options, self.pushButton_up)
        mainsettingDialog.setTabOrder(self.pushButton_up, self.pushButton_down)
        mainsettingDialog.setTabOrder(self.pushButton_down, self.pushButton_remove)
        mainsettingDialog.setTabOrder(self.pushButton_remove, self.pushButton_add)
        mainsettingDialog.setTabOrder(self.pushButton_add, self.lineEdit_x)
        mainsettingDialog.setTabOrder(self.lineEdit_x, self.lineEdit_y)
        mainsettingDialog.setTabOrder(self.lineEdit_y, self.lineEdit_Center)
        mainsettingDialog.setTabOrder(self.lineEdit_Center, self.lineEdit_End)
        mainsettingDialog.setTabOrder(self.lineEdit_End, self.lineEdit_Bright)
        mainsettingDialog.setTabOrder(self.lineEdit_Bright, self.lineEdit_stafps)
        mainsettingDialog.setTabOrder(self.lineEdit_stafps, self.comboBox_checksum)
        mainsettingDialog.setTabOrder(self.comboBox_checksum, self.pushButton_eyecatch)
        mainsettingDialog.setTabOrder(self.pushButton_eyecatch, self.lineEdit_eyecatch)
        mainsettingDialog.setTabOrder(self.lineEdit_eyecatch, self.pushButton_save)
        mainsettingDialog.setTabOrder(self.pushButton_save, self.pushButton_cancel)

    def retranslateUi(self, mainsettingDialog):
        mainsettingDialog.setWindowTitle(QtWidgets.QApplication.translate("mainsettingDialog", "Settings", None, -1))
        __sortingEnabled = self.listWidget_Options.isSortingEnabled()
        self.listWidget_Options.setSortingEnabled(False)
        self.listWidget_Options.item(0).setText(QtWidgets.QApplication.translate("mainsettingDialog", "Columns", None, -1))
        self.listWidget_Options.item(1).setText(QtWidgets.QApplication.translate("mainsettingDialog", "Thumbnail", None, -1))
        self.listWidget_Options.item(2).setText(QtWidgets.QApplication.translate("mainsettingDialog", "Xlsx output", None, -1))
        self.listWidget_Options.item(3).setText(QtWidgets.QApplication.translate("mainsettingDialog", "Misc", None, -1))
        self.listWidget_Options.setSortingEnabled(__sortingEnabled)
        self.pushButton_restore_columns.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Restore default Columns settings.", None, -1))
        self.pushButton_up.setText(QtWidgets.QApplication.translate("mainsettingDialog", "↑", None, -1))
        self.pushButton_down.setText(QtWidgets.QApplication.translate("mainsettingDialog", "↓", None, -1))
        self.label_Selected.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Selected Columns", None, -1))
        self.pushButton_remove.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Remove ->", None, -1))
        self.pushButton_add.setText(QtWidgets.QApplication.translate("mainsettingDialog", "<- Add", None, -1))
        self.label_Nonselective.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Non Selective Columns", None, -1))
        self.label_DD.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Use drag and drop to reorder Column items.", None, -1))
        self.pushButton_restore_thumb.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Restore default Thumbnail settings.", None, -1))
        self.groupBox_Thumbnailsize.setTitle(QtWidgets.QApplication.translate("mainsettingDialog", "Resolution", None, -1))
        self.label_y.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Y:", None, -1))
        self.label_x.setText(QtWidgets.QApplication.translate("mainsettingDialog", "X:", None, -1))
        self.label_stafps.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "If there are no fps metadata in the still image, Force fps by input.\n"
"By specifying it, you can display the length of the still picture sequence\n"
"without fps metadata.\n"
"Ex:sequence of jpg,tif,png....", None, -1))
        self.label_stafps.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Set virtual fps to still image sequence(ex:jpg,tif,tga):", None, -1))
        self.lineEdit_stafps.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "If there are no fps metadata in the still image, Force fps by input.\n"
"By specifying it, you can display the length of the still picture sequence\n"
"without fps metadata.\n"
"Ex:sequence of jpg,tif,png....", None, -1))
        self.label_stafps2.setText(QtWidgets.QApplication.translate("mainsettingDialog", "fps", None, -1))
        self.groupBox_ThumbnailParam.setTitle(QtWidgets.QApplication.translate("mainsettingDialog", "Image Enhance(default=1.0)", None, -1))
        self.label_Bright.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Adjust the brightness of the image.", None, -1))
        self.label_Bright.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Brightness:", None, -1))
        self.lineEdit_Bright.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Adjust the brightness of the image.", None, -1))
        self.groupBox_ThumbnailOffset.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Adjust thumbnail position when importing", None, -1))
        self.groupBox_ThumbnailOffset.setTitle(QtWidgets.QApplication.translate("mainsettingDialog", "Offset(sec.msec)", None, -1))
        self.lineEdit_End.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the end.\n"
"(Note: specify a negative value)", None, -1))
        self.lineEdit_Center.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the center.\n"
"If you want to specify the front from the center, specify minus", None, -1))
        self.lineEdit_Start.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the still/movie beginning", None, -1))
        self.label_Soffset.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the still/movie beginning", None, -1))
        self.label_Soffset.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Start Offset:", None, -1))
        self.label_Eoffset.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the end.\n"
"(Note: specify a negative value)", None, -1))
        self.label_Eoffset.setText(QtWidgets.QApplication.translate("mainsettingDialog", "End Offset:", None, -1))
        self.label_Coffset.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Import images after n.m seconds from the center.\n"
"If you want to specify the front from the center, specify minus", None, -1))
        self.label_Coffset.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Center Offset:", None, -1))
        self.groupBox_xlsxout.setTitle(QtWidgets.QApplication.translate("mainsettingDialog", "Xlsx output mode settings", None, -1))
        self.label_Note2.setText(QtWidgets.QApplication.translate("mainsettingDialog", "When sharing xlsx online, some web services (such as Google SpreadSheet)\n"
"may have limitations on the original xlsx file size.\n"
"In addition,\n"
"Image display may disappear when loading a large amount of rows.\n"
"Therefore,ShotList recommend \"book\" mode.\n"
"(You can avoid the problem by dividing the file into smaller pieces)\n"
"\n"
"\"all\" mode is useful when you want to combine all metadata into one file.\n"
"\"all\" and \"sheet\" mode may become huge xlsx file.", None, -1))
        self.label_Note.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Note:", None, -1))
        self.radioButton_book.setText(QtWidgets.QApplication.translate("mainsettingDialog", "book (Output xlsx file separately if Max rows exceeded)*", None, -1))
        self.radioButton_sheet.setText(QtWidgets.QApplication.translate("mainsettingDialog", "sheet (Output xlsx one file. add sheet if Max rows exceeded)", None, -1))
        self.radioButton_all.setText(QtWidgets.QApplication.translate("mainsettingDialog", "all (Output all rows in xlsx one file, one sheet)", None, -1))
        self.label_Maxrow.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Max rows:", None, -1))
        self.pushButton_restore_xlsx.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Restore default xlsx settings.", None, -1))
        self.pushButton_all_restore.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Restore \"ALL\" Default settings.", None, -1))
        self.checkBox_Disableseq.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Don\'t summarize Image Sequence files(One file One Thumbnail generate)", None, -1))
        self.comboBox_checksum.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "TIPS: The hash calculation can be omitted, if Setting is the same as RapidCopy hash setting.", None, -1))
        self.comboBox_checksum.setCurrentText(QtWidgets.QApplication.translate("mainsettingDialog", "(xxHash)", None, -1))
        self.comboBox_checksum.setItemText(0, QtWidgets.QApplication.translate("mainsettingDialog", "(xxHash)", None, -1))
        self.comboBox_checksum.setItemText(1, QtWidgets.QApplication.translate("mainsettingDialog", "(MD5)", None, -1))
        self.comboBox_checksum.setItemText(2, QtWidgets.QApplication.translate("mainsettingDialog", "(SHA1)", None, -1))
        self.label_checksum.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "TIPS: The hash calculation can be omitted, if Setting is the same as RapidCopy hash setting.", None, -1))
        self.label_checksum.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Hash Algorithm:", None, -1))
        self.label_eyecatch.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Embeds the specified image at the beginning of xlsx.\n"
"(Put your company logo etc.)\n"
"Note: The image size is up to 500 * 500", None, -1))
        self.label_eyecatch.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Xlsx eyecatch:", None, -1))
        self.pushButton_eyecatch.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Embeds the specified image at the beginning of xlsx.\n"
"(Put your company logo etc.)\n"
"Note: The image size is up to 500 * 500", None, -1))
        self.pushButton_eyecatch.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Select..", None, -1))
        self.lineEdit_eyecatch.setToolTip(QtWidgets.QApplication.translate("mainsettingDialog", "Embeds the specified image at the beginning of xlsx.\n"
"(Put your company logo etc.)\n"
"Note: The image size is up to 500 * 500", None, -1))
        self.checkBox_lang.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Enable Japanese UI  (off = English UI)", None, -1))
        self.pushButton_restore_misc.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Restore Misc Defaults settings.", None, -1))
        self.pushButton_save.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Save", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("mainsettingDialog", "Cancel", None, -1))

